[project]
name = "aoc25"
version = "0.1.0"
description = "Advent of Code 2025"
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["aocli"]

[dependency-groups]
dev = [
    "mypy>=1.19.0",
    "ruff>=0.14.9",
]

[tool.aocli]
solutions-pkg = "aoc.solution"
year = 2025

[tool.mypy]
strict = true

[tool.ruff.lint]
extend-select = ["I"]

[tool.uv.sources]
aocli = { workspace = true }

[tool.uv.workspace]
members = [
    "packages/aocli",
]
